### ISSUE TITLE
How to make min and max (mat) on nodejs

### ISSUE THREAD

**Issue by Aserus** [justadudewhohacks/opencv4nodejs#60] opened 2017-11-08 12:24 UTC
I have an example of a Python
I can not understand how to write it on a nodejs

I wrote a part of the example, but I'm not sure if this is correct

Python
```
gradX = cv2.Sobel(blackhat, ddepth=cv2.CV_32F, dx=1, dy=0, ksize=-1)
gradX = np.absolute(gradX)
(minVal, maxVal) = (np.min(gradX), np.max(gradX))
gradX = (255 * ((gradX - minVal) / (maxVal - minVal))).astype("uint8")
```

Nodejs
```
let gradX = blackhat.sobel(cv.CV_32F,1,0,-1);
gradX = gradX.abs();
let minVal = **???**
let maxVal = **???**

let v1 = gradX.sub(minVal);
let v2 = maxVal.sub(minVal);
let v3 = v1.hDiv(v2);
gradX = v3.mul(255);
```

**Comment by justadudewhohacks** [comment] 2017-11-08 12:38
Hey,
you can view function signature in the docs:

`{ minVal: Number, maxVal: Number, minLoc: Point2, maxLoc: Point2 } : mat.minMaxLoc(Mat mask = noArray())`

So you could try:
```
let minMax = gradX.minMaxLoc();
let minVal = minMax.minVal;
let maxVal = minMax.maxVal;
```

**Comment by Aserus** [comment] 2017-11-08 13:06
cool.
now I have stopped on how to take away the Number from the MAT ))

**Comment by Aserus** [comment] 2017-11-08 14:40
i have a very strange moment

**this is blackhut on python**

```
rectKernel = cv2.getStructuringElement(cv2.MORPH_RECT, (13, 5))
blackhat = cv2.morphologyEx(gray, cv2.MORPH_BLACKHAT, rectKernel)
```
![image](https://user-images.githubusercontent.com/10893615/32554638-885c6520-c4ab-11e7-8395-300393be9c1f.png)

**and this is blackhut on python**

`let blackhat = grey.morphologyEx(grey, cv.MORPH_BLACKHAT,new cv.Point(13, 5));`
![image](https://user-images.githubusercontent.com/10893615/32554661-9a75f2f8-c4ab-11e7-967f-37322d5c802d.png)


why did they turn out different??

**Comment by justadudewhohacks** [comment] 2017-11-08 14:48
The first parameter should be the kernel. You did pass it the grey image twice. Try something like this:
```
let kernelSize = new cv.Size(13, 5)
let rectKernel = cv.getStructuringElement(cv.MORPH_RECT, kernelSize)
let blackhat = grey.morphologyEx(rectKernel, cv.MORPH_BLACKHAT)
```

**Comment by Aserus** [comment] 2017-11-08 16:09
if I use cv.THRESH_BINARY then everything is fine, but if I use cv.THRESH_OTSU then I get an error

`let thresh = gradX.threshold(0,255,cv.THRESH_OTSU);`
or
`let thresh = gradX.threshold(0,255,cv.THRESH_BINARY |  cv.THRESH_OTSU);`

```
OpenCV Error: Assertion failed (src.type() == (((0) & ((1 << 3) - 1)) + (((1)-1) << 3))) in threshold, file /tmp/opencv-20171031-96694-16heojr/opencv-3.3.1/modules/imgproc/src/thresh.cpp, line 1402
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20171031-96694-16heojr/opencv-3.3.1/modules/imgproc/src/thresh.cpp:1402: error: (-215) src.type() == (((0) & ((1 << 3) - 1)) + (((1)-1) << 3)) in function threshold

./run: line 1: 15978 Abort trap: 6           node index.js
```

**Comment by justadudewhohacks** [comment] 2017-11-08 16:25
Strange, there is obviously something wrong with the flag. Flags are defined as follows:
```
enum ThresholdTypes {
    THRESH_BINARY     = 0,
    ...
    THRESH_OTSU       = 8
};
```

Can you try the following to make sure none of the flags is undefined:
```
console.log(cv.THRESH_BINARY) // should be 0
console.log(cv.THRESH_OTSU) // should be 8
```

If this is not working: `let thresh = gradX.threshold(0,255, 8);`, then I will check it later today.

**Comment by Aserus** [comment] 2017-11-08 16:49
I have in console
```
THRESH_BINARY = 0
THRESH_OTSU = 8
```

https://github.com/Aserus/node-mrz/tree/master

**Comment by justadudewhohacks** [comment] 2017-11-08 16:58
Ok I will check out when at home. Maybe it's also opencv3.3.1 related. Do you use an official release, opencv.3.3.1rc or an own build?

**Comment by Aserus** [comment] 2017-11-08 18:19
I user opencv: stable 3.3.1 (bottled) 
Installed from homebrew

**Comment by Aserus** [comment] 2017-11-08 18:23
I user opencv: stable 3.3.1 (bottled) 
Installed from homebrew

**Comment by Aserus** [comment] 2017-11-08 18:23
I use opencv: stable 3.3.1 (bottled) 
Installed from homebrew

**Comment by Aserus** [comment] 2017-11-08 18:25
I use opencv: stable 3.3.1 (bottled) 
Installed from homebrew

**Comment by justadudewhohacks** [comment] 2017-11-08 20:31
Hey just tested it and threshold with cv.THRESH_OTSU worked for me. However I think the issue is gradX is CV_32F right? I think opencv will let you threshold only CV_8U typed Mats. You could convert the type:
`gradX = gradX.convertTo(cv.CV_8U)`

**Comment by justadudewhohacks** [comment] 2017-12-08 09:01
Hey, is this still an issue or can I close it?

**Closed** 2017-12-17 12:28 UTC
