### ISSUE TITLE
autobuild Error  

### ISSUE THREAD

**Issue by zhengxinvip** [justadudewhohacks/opencv4nodejs#455] opened 2018-11-13 10:36 UTC
C:\WINDOWS\system32>npm install --save opencv4nodejs

> opencv-build@0.0.15 install C:\WINDOWS\system32\node_modules\opencv-build
> node ./install.js

info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info install library dir does not exist: C:\WINDOWS\system32\node_modules\opencv-build\opencv\build\lib\Release
info install running install script...
info install using msbuild: { path: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe',
info install   version: 15 }
Cloning into 'opencv_contrib'...
remote: Enumerating objects: 2149, done.
remote: Counting objects: 100% (2149/2149), done.
remote: Compressing objects: 100% (1897/1897), done.
remote: Total 2149 (delta 355), reused 1179 (delta 142), pack-reused 0
Receiving objects: 100% (2149/2149), 50.82 MiB | 146.00 KiB/s, done.
Resolving deltas: 100% (355/355), done.
Note: checking out '1f6d6f06266e1ef336437ae5404bee1c65d42cda'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Checking out files: 100% (1771/1771), done.
Cloning into 'opencv'...
remote: Enumerating objects: 7192, done.
remote: Counting objects: 100% (7192/7192), done.
remote: Compressing objects: 100% (6112/6112), done.
remote: Total 7192 (delta 1150), reused 3934 (delta 707), pack-reused 0
Receiving objects: 100% (7192/7192), 80.72 MiB | 147.00 KiB/s, done.
Resolving deltas: 100% (1150/1150), done.
Note: checking out 'b38c50b3d0c31e82294315ec44b54b7ef559ef12'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Checking out files: 100% (5967/5967), done.
CMake Error at CMakeLists.txt:127 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.8.169+g1ccb72aefa
    版权所有(C) Microsoft Corporation。保留所有权利。

    MSBUILD : error MSB1009: 项目文件不存在。
    开关:VCTargetsPath.vcxproj

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Windows/System32/node_modules/opencv-build/opencv/build/CMakeFiles/CMakeOutput.log".
ERR! child process exited with code 1
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.15 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS-1\AppData\Roaming\npm-cache\_logs\2018-11-13T08_30_00_021Z-debug.log

**Comment by zhengxinvip** [comment] 2018-11-13 12:01
[2018-11-13T11_51_27_695Z-debug.log](https://github.com/justadudewhohacks/opencv4nodejs/files/2576140/2018-11-13T11_51_27_695Z-debug.log)

**Comment by zhengxinvip** [comment] 2018-11-13 12:01
this is the log

**Comment by justadudewhohacks** [comment] 2018-11-16 08:53
Before trying to figure out what the root of the issue is, I would first of all not install the package in a directory, which contains whitespaces in the path (Program Files (x86)) as stated in the README.

**Comment by justadudewhohacks** [comment] 2018-12-02 13:54
Closing, if my last comment didn't help, feel free to reopen.

**Closed by justadudewhohacks** 2018-12-02 13:54 UTC
