### ISSUE TITLE
Add support for matchTemplate

### ISSUE THREAD

**Issue by Bfindlay** [justadudewhohacks/opencv4nodejs#12] opened 2017-10-08 12:23 UTC
I am wondering if there will be any support for the matchTemplate function anytime soon?
Thanks

**Comment by justadudewhohacks** [comment] 2017-10-08 12:30
Hey,

I can add it. Are you missing any further functions? You can list them here and I will add them with this PR.

**Comment by Bfindlay** [comment] 2017-10-08 12:38
As of now matchTemplate is the only one i am missing.
Thanks for the fast reply.

**Comment by justadudewhohacks** [comment] 2017-10-08 15:04
Merged and published. Let me know if something is not wokring as intended.

**Closed** 2017-10-21 10:05 UTC
