### ISSUE TITLE
cv.imShow() not working.

### ISSUE THREAD

**Issue by Topru** [justadudewhohacks/opencv4nodejs#375] opened 2018-08-08 12:34 UTC
I am running Debian Buster and I installed this package using npm install opencv4nodejs.

 When I try to run code with cv.imshow() I get this error:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  OpenCV Error: (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, in file /home/topias/imgproject/node_modules/opencv-build/opencv/opencv/modules/highgui/src/window.cpp, line 636, status -2`

Already tried installing libgtk2.0-dev and pkg-config and reinstalling opencv4nodejs after.

**Comment by justadudewhohacks** [comment] 2018-08-09 19:00
After installing libgtk2.0 you have to rebuild OpenCV. If you are using the auto build feature, make sure to purge opencv4nodejs and opencv-build from node_modules and reinstall opencv4nodejs.

**Comment by rainabba** [comment] 2018-08-11 17:48
I'm trying to build a docker container based on justadudewhohacks/opencv-nodejs:node9-opencv3.4.1-contrib and whether I install libgtk2.0-dev or not, I see the same error. Below is my development Dockerfile. Any ideas why I'm getting the GTK2.0 error also when I call calcHist()? I'm hoping this might help us both nail down the cause.

```DockerFile
FROM justadudewhohacks/opencv-nodejs:node9-opencv3.4.1-contrib

RUN apt-get update -y \
  && apt-get upgrade -y \
  && update-ca-certificates --fresh \
  && apt-cache policy ca-certificates \
  && apt-get install -y libgtk2.0-dev pkg-config build-essential wget libc6 \
  && npm install -g -y npm@6.1.0 \
  && npm install -g -y vim nodemon;

ARG DIRECTORY_NAME=form-parser
ARG PORTS_TO_EXPOSE=3000

# setup
RUN mkdir -p /root/${DIRECTORY_NAME}
WORKDIR /root/${DIRECTORY_NAME}

# install global dependencies
COPY . ./

# install local dependencies
RUN npm install --quiet --update-binary

# run build
RUN npm run build

# ports
EXPOSE ${PORTS_TO_EXPOSE}

# low-resource init
RUN echo "tail-file" > ./tail-file
CMD tail -f ./tail-file

CMD /bin/bash
```

**Comment by justadudewhohacks** [comment] 2018-08-11 17:55
I think you can't use the OpenCV GUI in a docker container. The error shouldn't be raised when calling `calcHist()`. Could you share the code you are running?

**Comment by rainabba** [comment] 2018-08-11 18:01
Ahh. Let me check my assumptions.

**Comment by rainabba** [comment] 2018-08-11 18:16
You nailed it. I left imshow() and waitKey() calls in my code :)

With xserver and gtk installed in the container (and working properly of course), would you expect that to work, or is there another limitation?

**Comment by justadudewhohacks** [comment] 2018-09-13 12:07
Closing for now, since the original issue was solved.

**Closed by justadudewhohacks** 2018-09-13 12:07 UTC
