### ISSUE TITLE
NPM install scripts can't handle spaces in folder names on MacOS

### ISSUE THREAD

**Issue by ch-luke** [justadudewhohacks/opencv4nodejs#91] opened 2017-12-03 21:44 UTC
Hi,

Been trying to install this NPM package for the last day and was struggling. Build kept failing with reference to a missing folder for "macro-inferno". Eventually moved the project to a path without spaces and now it works. Suggest either adding support for spaces or added a note in the readme.

Cheers,
Luke

**Comment by justadudewhohacks** [comment] 2017-12-04 07:56
Hi,

Thanks for the hint. Seems to be related to macOS only.

**Comment by wbern** [comment] 2018-06-14 08:31
@ch-luke within minimal information we'll close this for now. If anyone wants to dig up the cause of this again and provide fresh logs with other useful information like what npm version what used, we'll re-open the issue.

**Closed by wbern** 2018-06-14 08:31 UTC
