### ISSUE TITLE
Support for Scharr / Sobel  

### ISSUE THREAD

**Issue by smoscar** [justadudewhohacks/opencv4nodejs#14] opened 2017-10-09 01:25 UTC
Wondering if there are plans to support the Scharr / Sobel operators?
Thanks!

**Comment by justadudewhohacks** [comment] 2017-10-09 06:46
Definitely! :)

**Comment by justadudewhohacks** [comment] 2017-10-09 08:43
Merged and published. Let me know if something is not working as intended.

**Comment by smoscar** [comment] 2017-10-09 14:29
Awesome! 
It's working great, thanks for the quick response!

**Comment by justadudewhohacks** [comment] 2017-10-09 19:25
Great! You're welcome. Supporting this project, by leaving a star for the repo would of course be highly appreciated. :)

**Comment by smoscar** [comment] 2017-10-10 15:22
Sure thing

**Closed** 2017-10-12 21:22 UTC
