### ISSUE TITLE
opencv4nodejs/build/Release/opencv4nodejs.node: undefined symbol

### ISSUE THREAD

**Issue by komalpharate** [justadudewhohacks/opencv4nodejs#162] opened 2018-01-25 07:06 UTC
Opencv: v3.3.0
node : 8.9.4

Opencv4nodejs installation completed properly.
but after running the server getting the following error 

module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/nvidia/aggregator/jetson-device-client/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node: undefined symbol: _ZTVN2cv13HOGDescriptorE
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nvidia/aggregator/jetson-device-client/node_modules/opencv4nodejs/lib/opencv4nodejs.js:7:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

**Comment by justadudewhohacks** [comment] 2018-01-25 07:27
You are missing the runtime libraries.

If you are on windows you need to add the binaries to your path:
> Add an environment variable OPENCV_BIN_DIR pointing to the library dir containing the OpenCV .dll files.
> Append ;%OPENCV_BIN_DIR%; to your path variable.
> Note: Restart your current console session after making changes to your environment.

**Comment by komalpharate** [comment] 2018-01-25 09:18
Thanks,
I'm currently working on
Jetson TX2(Architecture ARM64) of nvidia ubuntu 16.04 
OpenCV 3.3.0
I did set the OPENCV_DIR variable and OPENCV_LIB_DIR variable as
export OPENCV_LIB_DIR=/usr/lib
export OPENCV_DIR=/usr
installation is done right.
And still getting the same error

**Comment by justadudewhohacks** [comment] 2018-01-25 10:01
Hm havent the .so libs of opencv been dynamically linked when you installed opencv? On ubuntu systems the libraries are usually installed in usr/local/lib and usr/local/bin

**Comment by komalpharate** [comment] 2018-01-25 10:17
On my machine OpenCV si installed in /usr/lib and /usr/bin directories. So I had to set those variables.

**Comment by justadudewhohacks** [comment] 2018-01-25 10:32
What's also strange is that it says missing symbol for hog descriptor `undefined symbol: _ZTVN2cv13HOGDescriptor`.

Did you build opencv yourself? If so, which cmake flags did you set, something cuda specific?

**Comment by komalpharate** [comment] 2018-01-25 10:33
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_PNG=OFF \
    -DBUILD_TIFF=OFF \
    -DBUILD_TBB=OFF \
    -DBUILD_JPEG=OFF \
    -DBUILD_JASPER=OFF \
    -DBUILD_ZLIB=OFF \
    -DBUILD_EXAMPLES=ON \
    -DBUILD_opencv_java=OFF \
    -DBUILD_opencv_python2=ON \
    -DBUILD_opencv_python3=OFF \
    -DENABLE_PRECOMPILED_HEADERS=OFF \
    -DWITH_OPENCL=OFF \
    -DWITH_OPENMP=OFF \
    -DWITH_FFMPEG=ON \
    -DWITH_GSTREAMER=ON \
    -DWITH_GSTREAMER_0_10=OFF \
    -DWITH_CUDA=ON \
    -DWITH_GTK=ON \
    -DWITH_VTK=OFF \
    -DWITH_TBB=ON \
    -DWITH_1394=OFF \
    -DWITH_OPENEXR=OFF \
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 \
    -DCUDA_ARCH_BIN=6.2 \
    -DCUDA_ARCH_PTX="" \
    -DINSTALL_C_EXAMPLES=ON \
    -DINSTALL_TESTS=ON \
    -DOPENCV_TEST_DATA_PATH=../opencv_extra/testdata \
    ../

This is the Cmake command i used

**Comment by komalpharate** [comment] 2018-01-25 10:34
https://github.com/jetsonhacks/buildOpenCVTX2
This is the link I referred

**Comment by justadudewhohacks** [comment] 2018-01-25 10:49
Ah I see. Looking at the makefile I am not sure if doing a `sudo ldconfig` after `make install` helps with the linking issue.

Otherwise it might be related to the cuda bindings that are generated, but I am not sure. I never tried to install opencv4nodejs with opencv built with cuda. In fact it also doesn't make sense, since you can not use cuda with opencv4nodejs anyways, since I have no bindings for cuda modules.

**Comment by komalpharate** [comment] 2018-01-25 10:53
Okay.
Thanks for your reply.
I will try to do so.

**Comment by komalpharate** [comment] 2018-01-25 11:09
Hey,
I changed the cmake 

-DCMAKE_INSTALL_PREFIX=/usr/local

Now getting this error 


../cc/modules/objdetect/HOGDescriptor.cc:591:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/opencv4nodejs/cc/modules/objdetect/HOGDescriptor.o.d.raw: No such file or directory
 }
 ^
compilation terminated.
opencv4nodejs.target.mk:208: recipe for target 'Release/obj.target/opencv4nodejs/cc/modules/objdetect/HOGDescriptor.o' failed
make: *** [Release/obj.target/opencv4nodejs/cc/modules/objdetect/HOGDescriptor.o] Error 1
make: Leaving directory '/home/nvidia/aggregator/jetson-device-client/node_modules/opencv4nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.38-tegra
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/nvidia/aggregator/jetson-device-client/node_modules/opencv4nodejs
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by justadudewhohacks** [comment] 2018-01-26 08:24
I would first of all purge all old opencv libraries before installing opencv again.

Here you can find a guide on how to install opencv on linux if you have trouble:
https://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html

Also I would disable all unnecessary builds of tests and examples, by adding the following cmake flags:
`-DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF`

**Comment by justadudewhohacks** [comment] 2018-02-23 08:48
Closing, if this is still an issue, feel free to reopen.

**Closed by justadudewhohacks** 2018-02-23 08:48 UTC

**Comment by cjntaylor** [comment] 2018-03-27 02:34
The symbol is missing because the module isn't properly linked against the right libraries when building against an OpenCV with CUDA enabled. In particular, your approach to finding libraries for a module is pretty badly flawed; in this case the search for the module `objdetect` picks up the module `cudaobjdetect` instead. This is similar to the issue and resulting "dirty fix" you had to implement around `dnn_objdetect` for 3.4.1 in `opencv-build`. 

With this library finding approach, I understand that the `Array.includes` filters out duplicates caused by symlinks, but it's also non-deterministic in the case where multiple, valid libraries contain the same keyword. 

My suggestion: Find the full module library name, e.g. `libopencv_objdetect.so` (where the `lib` prefix and `.so` suffix are platform dependent), and call `fs.realpath` on that to follow the possible symlink to the actual binary. I'd make a pull request to this effect, but since you seem to be in the middle of a transition to an external `opencv-build` I'm not quite sure where to make the change.

I'm not suggesting here that CUDA enabled modules themselves need to be supported, just that in the interim, their presence shouldn't break the module at runtime (it builds just fine without the symbols defined due to necessary node-gyp shenanigans). Since the CUDA modules are isolated from the CPU-based modules (an OpenCV built with CUDA support still provides/functions in CPU mode), there shouldn't be any reason you couldn't build this module against an install with it enabled.

**Comment by justadudewhohacks** [comment] 2018-03-27 06:40
I agree with what you said, a simple instring search of the module name seems to cause these kind of issues (linking dnn_objdetect and cuda modules instead of the plain objdetect lib).

I am not in the middle of any transition and the logic for finding the opencv libraries resides in the opencv-build package, in case you want to submit a PR.

Anyways, thanks for clarification here.

**Comment by komalpharate** [comment] 2018-03-27 08:48
Hi,
Is it possible to solve the bug somehow?

**Comment by justadudewhohacks** [comment] 2018-03-27 09:14
Currently working on it.

**Comment by komalpharate** [comment] 2018-03-27 13:10
Okay..Thanks

**Comment by komalpharate** [comment] 2018-08-01 07:28
Hi,
I would like to know if it is possible to solve the bug.

Thank you.
