### ISSUE TITLE
SimpleBlobDetector

### ISSUE THREAD

**Issue by cotejp** [justadudewhohacks/opencv4nodejs#42] opened 2017-10-29 00:03 UTC
It would be awesome to have bindings for SimpleBlobDetector. This is the kind of higher level object that allows a variety of opportunities.

Thanks for your great work!

**Comment by justadudewhohacks** [comment] 2017-10-29 14:57
SimpleBlobDetector is now available. Let me know if something is not working as intended or if you need something else.

**Comment by cotejp** [comment] 2017-10-29 17:59
Wow! That was amazingly fast! Thanks a lot. I'll give it a try this week and get back to you. Cheers!

**Comment by justadudewhohacks** [comment] 2017-12-08 09:03
Closing this issue. Let me know if you experience problems with the added bindings.

**Closed by justadudewhohacks** 2017-12-08 09:03 UTC
