### ISSUE TITLE
Unable to perform operations using houghLines

### ISSUE THREAD

**Issue by suprithwork** [justadudewhohacks/opencv4nodejs#182] opened 2018-02-26 14:23 UTC
const cannedImg = img.canny(30,160,3);

     const matRGBA = cannedImg.channels === 1
   ? cannedImg.cvtColor(cv.COLOR_GRAY2BGR)
    : cannedImg.cvtColor(cv.COLOR_BGR2GRAY);
   const houghImg = newImg.houghLinesP(1,(cv.PI)/180,30,0,0);

Hello,
        I am looking to perform cracks extraction from an image. Like if the biscuit is broken I want to detect the crack. I want to convert it to canny, then change the colorspace and then apply the houghlines transform and then perform some more operations.
I am getting weird errors like the below one 

OpenCV Error: Assertion failed (s >= 0) in setSize, file /Users/policendirekt/Documents/repositories/crack-detector/node_modules/opencv-build/opencv/opencv/modules/core/src/matrix.cpp, line 310
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/policendirekt/Documents/repositories/crack-detector/node_modules/opencv-build/opencv/opencv/modules/core/src/matrix.cpp:310: error: (-215) s >= 0 in function setSize

http://answers.opencv.org/question/102277/crack-detect-red-line-opencv/

The above link has exactly what I want to perform, but its in native c and I am unable to replicate the same using javascript. Can you please help me

**Comment by justadudewhohacks** [comment] 2018-02-28 09:27
Hi,

The issue is `cv.PI` is not defined. Use `Math.PI` instead and it should be fine. Also it should probably be 
```
 const matRGBA = cannedImg.channels === 1
  ? cannedImg
  : cannedImg.cvtColor(cv.COLOR_BGR2GRAY);
```
as `houghLinesP` expects a gray image.

**Comment by justadudewhohacks** [comment] 2018-03-24 19:34
Closing. If the issue remains, feel free to reopen.

**Closed by justadudewhohacks** 2018-03-24 19:34 UTC

**Comment by rainabba** [comment] 2019-03-14 20:45
For what it's worth, it looks to me like the op was expecting a mat back from houghLinesP when it returns an [ Vec4( x, y,  w, z ) ], which are 2 pairs of Point2() that can be fed to mat.drawLine() to visualize the lines found.

... now to get better control over houghLines and hopefully find a way to speed it up because it's easily 2x slower than any other process I'm running :(  To be fair though, there are a lot of small lines in my images.
